(function() {var implementors = {};
implementors['nue_io'] = ["impl&lt;T: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a> for <a class='struct' href='nue_io/struct.ReadWriteTell.html' title='nue_io::ReadWriteTell'>ReadWriteTell</a>&lt;T&gt;","impl&lt;T: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a> for <a class='struct' href='nue_io/struct.SeekForwardRead.html' title='nue_io::SeekForwardRead'>SeekForwardRead</a>&lt;T&gt;","impl&lt;T: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a> for <a class='struct' href='nue_io/struct.SeekAbsoluteRewind.html' title='nue_io::SeekAbsoluteRewind'>SeekAbsoluteRewind</a>&lt;T&gt;","impl&lt;T: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a> for <a class='struct' href='nue_io/struct.SeekAll.html' title='nue_io::SeekAll'>SeekAll</a>&lt;T&gt;","impl&lt;T: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Read.html' title='std::io::Read'>Read</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a> for <a class='struct' href='nue_io/struct.BufSeeker.html' title='nue_io::BufSeeker'>BufSeeker</a>&lt;T&gt;","impl&lt;T: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a> + <a class='trait' href='nue_io/trait.Tell.html' title='nue_io::Tell'>Tell</a> + <a class='trait' href='nue_io/trait.SeekAbsolute.html' title='nue_io::SeekAbsolute'>SeekAbsolute</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a> for <a class='struct' href='nue_io/struct.Region.html' title='nue_io::Region'>Region</a>&lt;T&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
