(function() {var implementors = {};
implementors['pod'] = ["impl&lt;T: <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='pod/code/struct.VecDecodeOptions.html' title='pod::code::VecDecodeOptions'>VecDecodeOptions</a>&lt;T&gt; <span class='where'>where T: <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a></span>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='pod/code/struct.StringDecodeOptions.html' title='pod::code::StringDecodeOptions'>StringDecodeOptions</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='pod/code/struct.CStringDecodeOptions.html' title='pod::code::CStringDecodeOptions'>CStringDecodeOptions</a>","impl&lt;B: <a class='trait' href='http://burntsushi.net/rustdoc/byteorder/byteorder/trait.ByteOrder.html' title='byteorder::ByteOrder'>ByteOrder</a>, T: <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> + <a class='trait' href='pod/endian/trait.EndianConvert.html' title='pod::endian::EndianConvert'>EndianConvert</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='pod/endian/struct.EndianPrimitive.html' title='pod::endian::EndianPrimitive'>EndianPrimitive</a>&lt;B, T&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
