[package]
name = "nue-macros"
version = "0.0.3"
authors = ["arcnmx"]

description = "POD and binary data encoding I/O macros"
documentation = "http://arcnmx.github.io/nue/pod/"
repository = "https://github.com/arcnmx/nue"
readme = "../README.md"
keywords = ["nue", "pod", "data", "encode", "endian"]
license = "MIT"

[lib]
name = "nue_macros"
plugin = true

[dependencies]
aster = "0.3"
quasi = "0.3"
quasi_macros = "0.3"

[dev-dependencies.nue-io]
version = "0.1"
path = "../io"

[dev-dependencies.pod]
version = "0.0.3"
features = ["unstable"]
path = "../pod"
